name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  deskpro_app_test_and_build:
    name: Test / Build
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --no-tags --depth=1 origin master

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get labels from pull request
        id: labels
        run: echo "milestone=$(jq --raw-output '.pull_request.labels[].name' $GITHUB_EVENT_PATH | grep -E 'major-version|minor-version' | head -1)" >> $GITHUB_OUTPUT

      - name: Prep local dev
        id: local-dev-prep
        run: |
          touch ~/.gitconfig
          mkdir ~/.ssh
          git config --global user.name "git log -1 --pretty=format:%an"
          git config --global user.email "$(git log -1 --pretty=format:%ae)"
          PREV_COMMIT=$(git log -1 --pretty=format:%H -- manifest.json)
          VERSION=$(git show ${{ steps.get-commit-hash.outputs.PREV_COMMIT }}:manifest.json | grep version | awk -F'"' '{print $4}')
          echo "Current Version is $VERSION"

      - name: Lint, Test, Build, and Tag
        uses: devcontainers/ci@v0.3
        env:
          MILESTONE: "${{ steps.labels.outputs.milestone }}"
          VERSION: "${{ steps.local-dev-prep.outputs.VERSION }}"
        with:
          env: |
            MILESTONE
            VERSION
          runCmd: |
            # Lint
            pnpm run lint
            pnpm tsc --noemit

            # Test
            pnpm test:coverage

            # Build
            pnpm run build

            # Tag
            if [ "$(git log -1 --pretty=format:%ae)" = "noreply@github.com" ]; then
              echo "Skipping workflow run because previous commit was not made by workflow."
              exit 0
            fi
            if [[ "$MILESTONE" == "major-version" ]]; then
              pnpm run bumpManifestVer major $VERSION
            elif [[ "$MILESTONE" == "minor-version" ]]; then
              pnpm run bumpManifestVer minor $VERSION
            else
              pnpm run bumpManifestVer patch $VERSION
            fi

      - name: Package app zip
        working-directory: dist
        run: |
          zip -rq ../app.zip *
          mv ../app.zip .
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: |
            dist/app.zip
            dist/manifest.json
          retention-days: 7

  deploy:
    uses: DeskproApps/app-template-vite/.github/workflows/subworkflow-deploy.yml@master
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    needs: [deskpro_app_test_and_build]
